#언어 및 jdk 설정
language: java
jdk:
- openjdk8

#푸쉬됬을 때 Travis를 통해 빌드 및 테스트를 자동화할 브랜치를 설정
branches:
  only:
  - master
## gradle 파일을 cache 하여 변경사항이 없다면 배포할때 캐쉬에 있는 설정을 이용하도록한다.
#cache:
#  directories:
#  - '$HOME/.m2/repository'
#  - '$HOME/.gradle'

#소스코드가 형상에 배포됬을때 실행할 명령어를 설정한다 (여기선 build를 진행)
script: "./gradlew clean build"

before_deploy:
- zip -r travis-CI *
- mkdir -p deploy
- mv travis-CI.zip deploy/travis-CI.zip

##build된 결과를 S3에 deploy 하도록 설정.
#deploy:
#- provider: s3
#  access_key_id: $AWS_ACCESS_KEY # IAM 사용자 생성시 발급받은 access_key_id
#  secret_access_key: $AWS_SECRET_KEY # IAM 사용자 생성시 발급받은 secret_access_key
#  bucket: kookooku-travis-deploy # 생성한 S3 버켓
#  region: ap-northeast-2  # 리전 설정
#  skip_cleanup: true
#  acl: public_read
#  local_dir: deploy
#  wait-until-deployed: true
#  on:
#    repo: songintae/TravisCI #Github 주소
#    branch: master  #배포할 브랜치 설정

#notifications을 설정하여 알림을 보낼 수 있다.
notifications:
  email:
    recipients:
    - songintae92@gmail.com

